name: CI
on:
  push:
    branches:
    - master

  schedule:
    - cron: "0 0 * * *"

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - run: deno task build --blogroll

    - name: Deploy
      uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad # v3.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: out/res
        force_orphan: true
